apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  #labels:
  #  label-one: "value-one"
  name: demo-app-subscription
  namespace: config-connector-demo-app
spec:
  ackDeadlineSeconds: 15
  messageRetentionDuration: 86400s # default; 7 days
  retainAckedMessages: false
  topicRef:
    name: demo-app-topic
  #deadLetterPolicy:
  #  deadLetterTopicRef:
  #    name: pubsubsubscription-dep2