apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-connector-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-connector-demo-app
  template:
    metadata:
      labels:
        app: config-connector-demo-app
        version: v1
    spec:
      serviceAccountName: demo-app-ksa
      containers:
      - name: config-connector-demo-app
        image: gcr.io/am01-services/config-connector-demo-app:latest # 'latest' tag is almost always a bad idea but this is just a demo
        ports:
          - name: http
            containerPort: 3000
        livenessProbe:
          httpGet:
              path: /
              port: 3000
              scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
        env:
          - name: project_id
            valueFrom:
              configMapKeyRef:
                name: config-connector-demo-app-configmap
                key: project_id
