apiVersion: "v1"
kind: "Service"
metadata:
  name: "config-connector-demo-app-svc"
  namespace: config-connector-demo-app
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: "config-connector-demo-app"
  type: "LoadBalancer"